//go:build ignore

// gen_keccakf_x8_avx512.go generates keccakf_x8_amd64.s — an 8-way batched
// Keccak-f[1600] using AVX-512F. Eight independent sponge states are
// interleaved lane-major: lane i of message j lives in st[8i+j], one 512-bit
// register (or memory row) per state lane, one message per 64-bit vector
// lane.
//
// Same ping-pong structure as the AVX2 4-way generator, but AVX-512 shrinks
// the round: VPROLQ is a single-instruction rotate (vs shift/shift/or) and
// VPTERNLOGQ computes chi's a^(~b&c) in one op ($0xD2 with operand order
// dst=a, src2=b, src3=c). Register plan per round:
//
//	Z0-Z4    chi inputs (post theta+rho+pi row)
//	Z5-Z9    theta D values
//	Z10-Z14  theta column parities (dead after D)
//	Z15      scratch (chi out)
//
// Usage: go run gen_keccakf_x8_avx512.go

package main

import (
	"fmt"
	"os"
)

var rc = [24]uint64{
	0x0000000000000001, 0x0000000000008082,
	0x800000000000808a, 0x8000000080008000,
	0x000000000000808b, 0x0000000080000001,
	0x8000000080008081, 0x8000000000008009,
	0x000000000000008a, 0x0000000000000088,
	0x0000000080008009, 0x000000008000000a,
	0x000000008000808b, 0x800000000000008b,
	0x8000000000008089, 0x8000000000008003,
	0x8000000000008002, 0x8000000000000080,
	0x000000000000800a, 0x800000008000000a,
	0x8000000080008081, 0x8000000000008080,
	0x0000000080000001, 0x8000000080008008,
}

type lane struct {
	idx int
	rot int
}

// Same combined rho+pi table as the other generators.
var groups = [5][5]lane{
	{{0, 0}, {6, 44}, {12, 43}, {18, 21}, {24, 14}},
	{{3, 28}, {9, 20}, {10, 3}, {16, 45}, {22, 61}},
	{{1, 1}, {7, 6}, {13, 25}, {19, 8}, {20, 18}},
	{{4, 27}, {5, 36}, {11, 10}, {17, 15}, {23, 56}},
	{{2, 62}, {8, 55}, {14, 39}, {15, 41}, {21, 2}},
}

const (
	rateLanes = 17
	fsize     = 1600 // 25 lanes × 64 bytes
)

var bufReg = [8]string{"R8", "R9", "R10", "R11", "R12", "R13", "R14", "R15"}

var p func(string, ...any)

func off(idx int, array bool) string {
	o := idx * 64
	base := "SP"
	if array {
		base = "DI"
	}
	return fmt.Sprintf("%d(%s)", o, base)
}

func main() {
	f, err := os.Create("keccakf_x8_amd64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	p = func(format string, args ...any) { fmt.Fprintf(f, format+"\n", args...) }

	p("// Code generated by gen_keccakf_x8_avx512.go. DO NOT EDIT.")
	p("")
	p("//go:build amd64 && !purego")
	p("")
	p("#include \"textflag.h\"")
	p("")
	p("// func keccakF1600AVX512x8(st *[200]uint64, bufs *[8]*byte, blocks int)")
	p("// Absorbs and permutes `blocks` rate-sized blocks of eight interleaved")
	p("// messages (lane i of message j at st[8i+j]).")
	p("TEXT ·keccakF1600AVX512x8(SB), 0, $%d-24", fsize)
	p("\tMOVQ st+0(FP), DI")
	p("\tMOVQ bufs+8(FP), AX")
	for i, r := range bufReg {
		p("\tMOVQ %d(AX), %s", i*8, r)
	}
	p("\tMOVQ blocks+16(FP), AX")
	p("")
	p("\tTESTQ AX, AX")
	p("\tJLE done")
	p("")
	p("block_loop:")

	// Absorb: gather lane i of each of the 8 messages into one zmm.
	// X0-X3 are free here (the round working set is only live inside a
	// round); VPINSRQ stays in its VEX form (xmm0-15), keeping the kernel
	// AVX-512F-only.
	p("\t// Gather lane i of each message into one zmm and XOR into the state.")
	for i := 0; i < rateLanes; i++ {
		for q := 0; q < 4; q++ {
			p("\tVMOVQ %d(%s), X%d", i*8, bufReg[2*q], q)
			p("\tVPINSRQ $1, %d(%s), X%d, X%d", i*8, bufReg[2*q+1], q, q)
		}
		for q := 0; q < 4; q++ {
			p("\tVINSERTI32X4 $%d, X%d, Z25, Z25", q, q)
		}
		p("\tVPXORQ %d(DI), Z25, Z25", i*64)
		p("\tVMOVDQU64 Z25, %d(DI)", i*64)
	}
	for _, r := range bufReg {
		p("\tADDQ $136, %s", r)
	}

	for round := 0; round < 24; round++ {
		p("")
		p("\t// Round %d", round)
		emitRound((round%2) == 0, round)
	}

	p("")
	p("\tDECQ AX")
	p("\tJNZ block_loop")
	p("")
	p("done:")
	p("\tVZEROUPPER")
	p("\tRET")
	p("")

	for i, c := range rc {
		p("DATA rc_x8<>+0x%02x(SB)/8, $0x%016x", i*8, c)
	}
	p("GLOBL rc_x8<>(SB), NOPTR|RODATA, $192")
}

func emitRound(srcArray bool, round int) {
	// Theta: column parities C[0..4] → Z10-Z14.
	for c := 0; c < 5; c++ {
		p("\tVMOVDQU64 %s, Z%d", off(c, srcArray), 10+c)
		for r := 1; r < 5; r++ {
			p("\tVPXORQ %s, Z%d, Z%d", off(r*5+c, srcArray), 10+c, 10+c)
		}
	}

	// D[x] = C[(x+4)%5] ^ rol(C[(x+1)%5], 1) → Z5-Z9.
	for x := 0; x < 5; x++ {
		p("\tVPROLQ $1, Z%d, Z%d", 10+(x+1)%5, 5+x)
		p("\tVPXORQ Z%d, Z%d, Z%d", 10+(x+4)%5, 5+x, 5+x)
	}

	// Five chi groups.
	for g := 0; g < 5; g++ {
		// B[i] = rol(src[l.idx] ^ D[l.idx%5], l.rot).
		for i := 0; i < 5; i++ {
			l := groups[g][i]
			p("\tVMOVDQU64 %s, Z%d", off(l.idx, srcArray), i)
			p("\tVPXORQ Z%d, Z%d, Z%d", 5+l.idx%5, i, i)
			if l.rot != 0 {
				p("\tVPROLQ $%d, Z%d, Z%d", l.rot, i, i)
			}
		}
		// out[j] = B[j] ^ (~B[j+1] & B[j+2]) via one ternlog
		// ($0xD2: dst ^ (~src2 & src3)); iota folded in with an
		// embedded-broadcast XOR on lane 0.
		for j := 0; j < 5; j++ {
			p("\tVMOVDQA64 Z%d, Z15", j)
			p("\tVPTERNLOGQ $0xD2, Z%d, Z%d, Z15", (j+2)%5, (j+1)%5)
			if g == 0 && j == 0 {
				p("\tVPXORQ.BCST rc_x8<>+0x%02x(SB), Z15, Z15", round*8)
			}
			p("\tVMOVDQU64 Z15, %s", off(g*5+j, !srcArray))
		}
	}
}
