//go:build ignore

// gen_keccakf_x4_avx2.go generates keccakf_x4_amd64.s — a 4-way batched
// Keccak-f[1600] using AVX2. Four independent sponge states are interleaved
// lane-major: lane i of message j lives in st[4i+j], one 256-bit register
// (or memory row) per state lane, one message per 64-bit vector lane.
//
// Structure mirrors the BMI2 single-lane generator: the state ping-pongs
// between the caller's array (DI) and an 800-byte stack buffer each round,
// with a 16-register working set per round:
//
//	Y0-Y4    chi inputs (post theta+rho+pi row)
//	Y5-Y9    theta D values
//	Y10-Y14  theta column parities (dead after D; Y10 reused for the
//	         broadcast round constant, Y11 as the chi scratch)
//	Y15      rotate scratch
//
// The kernel absorbs `blocks` consecutive rate-sized blocks of each message
// (fused XOR+permute, buffer pointers advance internally).
//
// Usage: go run gen_keccakf_x4_avx2.go

package main

import (
	"fmt"
	"os"
)

var rc = [24]uint64{
	0x0000000000000001, 0x0000000000008082,
	0x800000000000808a, 0x8000000080008000,
	0x000000000000808b, 0x0000000080000001,
	0x8000000080008081, 0x8000000000008009,
	0x000000000000008a, 0x0000000000000088,
	0x0000000080008009, 0x000000008000000a,
	0x000000008000808b, 0x800000000000008b,
	0x8000000000008089, 0x8000000000008003,
	0x8000000000008002, 0x8000000000000080,
	0x000000000000800a, 0x800000008000000a,
	0x8000000080008081, 0x8000000000008080,
	0x0000000080000001, 0x8000000080008008,
}

type lane struct {
	idx int // state lane index (0–24)
	rot int // left-rotation amount
}

// Chi groups: each group reads 5 lanes (after theta+rho+pi)
// and produces 5 consecutive output lanes. Same table as the BMI2 generator.
var groups = [5][5]lane{
	{{0, 0}, {6, 44}, {12, 43}, {18, 21}, {24, 14}}, // → lanes 0–4
	{{3, 28}, {9, 20}, {10, 3}, {16, 45}, {22, 61}}, // → lanes 5–9
	{{1, 1}, {7, 6}, {13, 25}, {19, 8}, {20, 18}},   // → lanes 10–14
	{{4, 27}, {5, 36}, {11, 10}, {17, 15}, {23, 56}}, // → lanes 15–19
	{{2, 62}, {8, 55}, {14, 39}, {15, 41}, {21, 2}}, // → lanes 20–24
}

const (
	rateLanes = 17  // 136 / 8
	fsize     = 800 // 25 lanes × 32 bytes for the temp state
)

var bufReg = [4]string{"R8", "R9", "R10", "R11"}

var p func(string, ...any)

// off returns the memory operand for interleaved lane idx.
func off(idx int, array bool) string {
	o := idx * 32
	base := "SP"
	if array {
		base = "DI"
	}
	return fmt.Sprintf("%d(%s)", o, base)
}

func main() {
	f, err := os.Create("keccakf_x4_amd64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	p = func(format string, args ...any) { fmt.Fprintf(f, format+"\n", args...) }

	p("// Code generated by gen_keccakf_x4_avx2.go. DO NOT EDIT.")
	p("")
	p("//go:build amd64 && !purego")
	p("")
	p("#include \"textflag.h\"")
	p("")
	p("// func keccakF1600AVX2x4(st *[100]uint64, b0, b1, b2, b3 *byte, blocks int)")
	p("// Absorbs and permutes `blocks` rate-sized blocks of four interleaved")
	p("// messages (lane i of message j at st[4i+j]).")
	p("TEXT ·keccakF1600AVX2x4(SB), 0, $%d-48", fsize)
	p("\tMOVQ st+0(FP), DI")
	p("\tMOVQ b0+8(FP), R8")
	p("\tMOVQ b1+16(FP), R9")
	p("\tMOVQ b2+24(FP), R10")
	p("\tMOVQ b3+32(FP), R11")
	p("\tMOVQ blocks+40(FP), R12")
	p("")
	p("\tTESTQ R12, R12")
	p("\tJLE done")
	p("")
	p("block_loop:")

	// Absorb: XOR one rate-sized block of each message into the state.
	p("\t// Gather lane i of each message into one ymm and XOR into the state.")
	for i := 0; i < rateLanes; i++ {
		p("\tVMOVQ %d(R8), X15", i*8)
		p("\tVPINSRQ $1, %d(R9), X15, X15", i*8)
		p("\tVMOVQ %d(R10), X14", i*8)
		p("\tVPINSRQ $1, %d(R11), X14, X14", i*8)
		p("\tVINSERTI128 $1, X14, Y15, Y15")
		p("\tVPXOR %d(DI), Y15, Y15", i*32)
		p("\tVMOVDQU Y15, %d(DI)", i*32)
	}
	for _, r := range bufReg {
		p("\tADDQ $136, %s", r)
	}

	for round := 0; round < 24; round++ {
		p("")
		p("\t// Round %d", round)
		emitRound((round%2) == 0, round)
	}

	p("")
	p("\tDECQ R12")
	p("\tJNZ block_loop")
	p("")
	p("done:")
	p("\tVZEROUPPER")
	p("\tRET")
	p("")

	// Round-constant table.
	for i, c := range rc {
		p("DATA rc_x4<>+0x%02x(SB)/8, $0x%016x", i*8, c)
	}
	p("GLOBL rc_x4<>(SB), NOPTR|RODATA, $192")
}

// srcArray: true = source is the array (DI), dest is the stack (SP);
// false = the reverse.
func emitRound(srcArray bool, round int) {
	// Theta: column parities C[0..4] → Y10-Y14.
	for c := 0; c < 5; c++ {
		p("\tVMOVDQU %s, Y%d", off(c, srcArray), 10+c)
		for r := 1; r < 5; r++ {
			p("\tVPXOR %s, Y%d, Y%d", off(r*5+c, srcArray), 10+c, 10+c)
		}
	}

	// D[x] = C[(x+4)%5] ^ rol(C[(x+1)%5], 1) → Y5-Y9 (the D register
	// doubles as the second rotate temp).
	for x := 0; x < 5; x++ {
		cx1 := 10 + (x+1)%5
		cx4 := 10 + (x+4)%5
		d := 5 + x
		p("\tVPSLLQ $1, Y%d, Y15", cx1)
		p("\tVPSRLQ $63, Y%d, Y%d", cx1, d)
		p("\tVPOR Y15, Y%d, Y%d", d, d)
		p("\tVPXOR Y%d, Y%d, Y%d", cx4, d, d)
	}

	// C registers are dead now; Y10 holds the broadcast round constant and
	// Y11 is the chi scratch for the rest of the round.
	p("\tVPBROADCASTQ rc_x4<>+0x%02x(SB), Y10", round*8)

	// Five chi groups.
	for g := 0; g < 5; g++ {
		// Load the row: B[i] = rol(src[l.idx] ^ D[l.idx%5], l.rot).
		for i := 0; i < 5; i++ {
			l := groups[g][i]
			p("\tVMOVDQU %s, Y%d", off(l.idx, srcArray), i)
			p("\tVPXOR Y%d, Y%d, Y%d", 5+l.idx%5, i, i)
			if l.rot != 0 {
				p("\tVPSLLQ $%d, Y%d, Y15", l.rot, i)
				p("\tVPSRLQ $%d, Y%d, Y%d", 64-l.rot, i, i)
				p("\tVPOR Y15, Y%d, Y%d", i, i)
			}
		}
		// out[j] = B[j] ^ (~B[j+1] & B[j+2]), iota on lane 0.
		for j := 0; j < 5; j++ {
			p("\tVPANDN Y%d, Y%d, Y11", (j+2)%5, (j+1)%5)
			p("\tVPXOR Y%d, Y11, Y11", j)
			if g == 0 && j == 0 {
				p("\tVPXOR Y10, Y11, Y11")
			}
			p("\tVMOVDQU Y11, %s", off(g*5+j, !srcArray))
		}
	}
}
